apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
        - name: ai-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5001
          env:
          - name: OLLAMA_BASE_URL
            value: {{ .Values.ollama.baseUrl | quote }}
          envFrom:
          - secretRef:
              name: openai-ai-secret

