apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
        - name: ai-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5001
          command: ["sh", "-c"]
          args:
            - "python server.py && tail -f /dev/null"
          env:
          - name: OLLAMA_BASE_URL
            value: {{ .Values.ollama.baseUrl | quote }}
          envFrom:
          - secretRef:
              name: openai-secret  
          volumeMounts:
            - name: github-ssh-key
              mountPath: /root/.ssh/id_ed25519
              subPath: id_ed25519
              readOnly: true
            - name: github-known-hosts
              mountPath: /root/.ssh/known_hosts
              subPath: known_hosts
              readOnly: true
      volumes:
        - name: github-ssh-key
          secret:
            secretName: github-ssh-secret
            items:
              - key: GH_SECRET
                path: id_ed25519
        - name: github-known-hosts
          secret:
            secretName: github-known-hosts-secret
            items:
              - key: known_hosts
                path: known_hosts
