apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-agent
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5001
