replicaCount: 1

image:
  repository: helm-linter
  tag: v0.1.3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30081

resources: {}

ingress:
  enabled: false

persistence:
  enabled: false
  volumeName: helm-linter-data
  mountPath: /app/data

ollama:
  baseUrl: http://ollama.devops-ai.svc.cluster.local:11434