replicaCount: 1

image:
  repository: localhost:5000/helm-linter
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30081

resources: {}

ingress:
  enabled: false

persistence:
  enabled: false
  volumeName: helm-linter-data
  mountPath: /app/data

ollama:
  baseUrl: http://ollama.devops-ai.svc.cluster.local:11434

revisionHistoryLimit: 3