apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcgm-exporter
  namespace: argocd
spec:
  project: devops-ai-project
  source:
    repoURL: git@github.com/dorado-ai-devops/devops-ai-lab.git
    targetRevision: HEAD
    path: helm-nvidia-dcgm
    helm:
      valueFiles:
        - ../argocd/values_nvidia.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
