image:
  repository: jenkins-helm
  tag: v0.1.2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  agentPort: 50000
  nodePort: 30080
  agentNodePort: 30050

pvc:
  existingClaim: jenkins-pvc
