image:
  repository: localhost:5000/jenkins-helm
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  agentPort: 50000
  nodePort: 30080
  agentNodePort: 30050

pvc:
  existingClaim: jenkins-pvc
