apiVersion: v1
kind: Service
metadata:
  name: ai-vector-bd
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-vector-bd
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8888
