image:
  repository: localhost:5000/nerf-trainer
  tag: "v0.1.9"
  pullPolicy: IfNotPresent

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    cpu: "6"
    memory: "8Gi"
    nvidia.com/gpu: 1

volume:
  pvcName: pvc-datos-nerf
  mountPath: /data

datasetName: lego-ds
imgCopyMode: TOTAL
imgType: png

init:
  image:
    repository: localhost:5000/colmap-init
    tag: "v0.1.21"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "6"
      memory: "6Gi"
    limits:
      cpu: "6"
      memory: "8Gi"

