image:
  repository: localhost:5000/nerf-trainer
  tag: "v0.1.3"
  pullPolicy: IfNotPresent

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    cpu: "3"
    memory: "4Gi"
    nvidia.com/gpu: 1

volume:
  pvcName: pvc-datos-nerf
  mountPath: /data

datasetName: lego-ds
imgCopyMode: TOTAL
imgType: png

init:
  image:
    repository: localhost:5000/colmap-init
    tag: "v0.1.9"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "2"
      memory: "2Gi"
    limits:
      cpu: "3"
      memory: "4Gi"

