image:
  repository: localhost:5000/nerf-trainer
  tag: "v3.0.14"
  pullPolicy: IfNotPresent

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    cpu: "6"
    memory: "8Gi"
    nvidia.com/gpu: 1

volume:
  pvcName: pvc-datos-nerf
  mountPath: /data

#Prepare dataset
prepareData: true
#Values dataset
datasetName: access-virus-ds
imgCopyMode: TOTAL
imgType: jpg


#Values training
nSteps: 15000
fastNerf: true # True-> fastNerf on false -> standalone ngp

init:
  image:
    repository: localhost:5000/colmap-init
    tag: "v4.0.14"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "6"
      memory: "6Gi"
    limits:
      cpu: "6"
      memory: "8Gi"

