apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never

      initContainers:
        - name: clone-dataset
          image: alpine/git
          env:
            - name: GH_KEY
              valueFrom:
                secretKeyRef:
                  name: github-ssh-secret
                  key: GH_SECRET
          command:
            - sh
            - -c
            - |
              set -e
              rm -rf /data/tmp_cloned && \
              echo "Clonando dataset desde GitHub..." && \
              mkdir -p /root/.ssh && \
              echo "$GH_KEY" > /root/.ssh/id_rsa && \
              chmod 600 /root/.ssh/id_rsa && \
              ssh-keyscan github.com >> /root/.ssh/known_hosts && \
              git clone git@github.com:dorado-ai-devops/ai-nerf-datasets.git /data/tmp_cloned && \
              mkdir -p /data/images && \
              cp -r /data/tmp_cloned/{{ .Values.datasetName }}/images/* /data/images && \
              [ "$(ls -A /data/images)" ] || (echo "No se copiaron imágenes. Abortando." && exit 1)
              sleep infinity
          volumeMounts:
            - name: nerf-data
              mountPath: /data

      containers:
        - name: nerf-trainer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nerf-data
              mountPath: {{ .Values.volume.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - "{{ .Values.scenePath }}"

      volumes:
        - name: nerf-data
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvcName }}

      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
