apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
#Init container para clonar el dataset desde GitHub
      initContainers:
        - name: clone-dataset
          image: alpine/git
          command:
            - sh
            - -c
            - |
              mkdir -p /root/.ssh && \
              cp /secrets/GH_SECRET /root/.ssh/id_rsa && \
              chmod 600 /root/.ssh/id_rsa && \
              ssh-keyscan github.com >> /root/.ssh/known_hosts && \
              git clone git@github.com:dorado-ai-devops/ai-nerf-datasets.git /data/tmp && \
              mkdir -p /data/images && \
              cp -r /data/tmp/{{ .Values.datasetName }}/images/* /data/images
          volumeMounts:
            - name: nerf-data
              mountPath: /data
            - name: ssh-secret
              mountPath: /secrets
              readOnly: true
#El contenedor principal que entrena el modelo NeRF
      containers:
        - name: nerf-trainer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nerf-data
              mountPath: {{ .Values.volume.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - "{{ .Values.scenePath }}"

      volumes:
        - name: nerf-data
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvcName }}
        - name: ssh-secret
          secret:
            secretName: github-ssh-secret

      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
