apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
{{- if eq .Values.prepareData true }}
      initContainers:
        - name: prepare-dataset
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          env:
            - name: GH_KEY
              valueFrom:
                secretKeyRef:
                  name: github-ssh-secret
                  key: GH_SECRET
            - name: DATASET_NAME
              value: "{{ .Values.datasetName }}"
            - name: IMG_COPY_MODE
              value: "{{ .Values.imgCopyMode }}"
            - name: DATA_PATH
              value: "{{ .Values.volume.mountPath }}/{{ .Values.datasetName }}"
            - name: IMG_TYPE
              value: "{{ .Values.imgType }}"
            - name: N_STEPS
              value: "{{ .Values.nSteps }}"
            - name: FAST
              value: "{{ .Values.fastNerf }}"
          volumeMounts:
            - name: nerf-data
              mountPath: {{ .Values.volume.mountPath }}
{{- end }}
      containers:
        - name: nerf-trainer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nerf-data
              mountPath: {{ .Values.volume.mountPath }}
          env:
            - name: DATA_PATH
              value: "{{ .Values.volume.mountPath }}/{{ .Values.datasetName }}"
            - name: FAST
              value: "{{ .Values.fastNerf }}"
            - name: N_STEPS
              value: "{{ .Values.nSteps }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: nerf-data
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvcName }}

      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
