replicaCount: 1

image:
  repository: localhost:5000/ai-vector-bd
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888

resources: {}

nodeSelector: {}

tolerations: []

affinity: []

volumes:
  data:
    hostPath: /mnt/data/chroma
