replicaCount: 1

image:
  repository: ai-vector-bd
  tag: v0.1.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888

resources: {}

nodeSelector: {}

tolerations: []

affinity: []

volumes:
  data:
    hostPath: /mnt/data/chroma
