apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
