replicaCount: 1

image:
  repository: localhost:5000/ai-pipeline-gen
  tag: "v1.0.1"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30974  # Asegúrate que esté libre

ollama:
  baseUrl: "http://ollama.devops-ai.svc.cluster.local:11434"
  
revisionHistoryLimit: 3