replicaCount: 1

image:
  repository: localhost:5000/ai-mcp-server
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001

volumeMount:
  mountPath: /mnt/data/mcp
  hostPath: /mnt/data/mcp
