apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-chat-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:dorado-ai-devops/devops-ai-lab.git
    targetRevision: HEAD
    path: manifests/helm-chat-ui
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
