apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: devops-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:12
          securityContext:
            privileged: true
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /exports && chmod 777 /exports
              echo "/exports *(rw,sync,no_subtree_check,no_root_squash)" > /etc/exports
              rpcbind
              rpc.nfsd 8
              exportfs -rv
              exec tail -f /dev/null
          ports:
            - containerPort: 2049
            - containerPort: 111
          volumeMounts:
            - name: nfs-data
              mountPath: /exports
      volumes:
        - name: nfs-data
          emptyDir: {}
