apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: devops-ai
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exports
    server: nfs-server.devops-ai.svc.cluster.local
