apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-linter
  namespace: devops-ai
  labels:
    app: helm-linter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-linter
  template:
    metadata:
      labels:
        app: helm-linter
    spec:
      containers:
      - name: helm-linter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: OLLAMA_BASE_URL
          value: {{ .Values.ollama.baseUrl | quote }}
        envFrom:
        - secretRef:
            name: openai-secret