apiVersion: v1
kind: Service
metadata:
  name: helm-linter-service
  namespace: devops-ai
spec:
  selector:
    app: helm-linter
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5001
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
