replicaCount: 1

image:
  repository: localhost:5000/ai-agent
  tag: "v1.0.9"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6001

resources: {}

nodeSelector: {}

tolerations: []

affinity: []

ollama:
  baseUrl: http://ollama.devops-ai.svc.cluster.local:11434

aiVendor: ollama
llmModel: llama3.1

revisionHistoryLimit: 3
