replicaCount: 1

image:
  repository: ai-agent
  tag: v0.3.50
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6001

resources: {}

nodeSelector: {}

tolerations: []

affinity: []

ollama:
  baseUrl: http://ollama.devops-ai.svc.cluster.local:11434
aiVendor: openai

revisionHistoryLimit: 3
