replicaCount: 1

image:
  repository: ai-agent
  tag: v0.3.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5001

resources: {}

nodeSelector: {}

tolerations: []

affinity: []

ollama:
  baseUrl: http://ollama.devops-ai.svc.cluster.local:11434

revisionHistoryLimit: 3
