apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: ssh-known-hosts
          mountPath: /var/jenkins_home/.ssh/known_hosts
          subPath: known_hosts
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: ssh-known-hosts
        configMap:
          name: jenkins-known-hosts
