apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-pipeline-gen.fullname" . }}
  namespace: devops-ai
  labels:
    app: pipeline-gen
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pipeline-gen
  template:
    metadata:
      labels:
        app: pipeline-gen
    spec:
      containers:
        - name: pipeline-gen
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5003
          env:
            - name: OLLAMA_BASE_URL
              value: {{ .Values.ollama.baseUrl | quote }}
