replicaCount: 1

image:
  repository: localhost:5000/ai-ollama
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 11434

persistence:
  enabled: true
  mountPath: /root/.ollama
  volumeName: ollama-data
  existingClaim: ollama-pvc
