replicaCount: 1

image:
  repository: localhost:5000/ai-chat-ui
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6501

resources: {}

nodeSelector: {}

tolerations: []

affinity: []

revisionHistoryLimit: 3
