apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: devops-ai-project
  source:
    repoURL: git@github.com/dorado-ai-devops/devops-ai-lab.git
    targetRevision: HEAD
    path: manifests/helm-jenkins
    helm:
      valueFiles:
        - ../jenkins/argocd/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops-ai
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
