apiVersion: v1
kind: Service
metadata:
  name: ai-mcp-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-mcp-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
