replicaCount: 1

image:
  repository: ai-gateway
  tag: v0.1.1
  pullPolicy: IfNotPresent

service:
  port: 5002
  type: NodePort
  nodePort: 30502
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
