replicaCount: 1

image:
  repository: ollama/ollama
  tag: cuda              # Imagen compatible con CUDA/GPU
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"
    nvidia.com/gpu: 1

service:
  type: ClusterIP
  port: 11434

persistence:
  enabled: true
  mountPath: /root/.ollama
  volumeName: ollama-data
  existingClaim: ollama-pvc

revisionHistoryLimit: 3
