replicaCount: 1

image:
  repository: localhost:5000/ai-ollama
  tag: "1.0.5"
  pullPolicy: IfNotPresent

env:
  - name: OLLAMA_NEW_ENGINE
    value: "true"
  - name: OLLAMA_DEBUG
    value: "DEBUG"
  - name: OLLAMA_KEEP_ALIVE
    value: "5m"
  # Alinea la ruta de modelos con el PVC montado
  - name: OLLAMA_MODELS
    value: /root/.ollama

resources:
  requests:
    cpu: "2"
    memory: "8Gi"
  limits:
    cpu: "4"
    memory: "16Gi"
    nvidia.com/gpu: 1

service:
  type: ClusterIP
  port: 11434

persistence:
  enabled: true
  mountPath: /root/.ollama
  volumeName: ollama-data
  existingClaim: ollama-pvc

revisionHistoryLimit: 3
