name: Auto PR from develop to main

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Auto update PR: develop → main'
          branch: develop         # rama origen
          base: main             # rama destino
          title: 'Auto PR: Sync develop into main'
          body: 'Automated PR created to merge changes from develop into main branch.'
          draft: false
          labels: automated-pr
