apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chat-ui
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ai-chat-ui
  template:
    metadata:
      labels:
        app: ai-chat-ui
    spec:
      containers:
        - name: chat-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6501
          # Si quieres variables extra, añádelas aquí:
          # env:
          #   - name: API_URL
          #     value: "http://ai-agent-service:5001"
