apiVersion: v1
kind: Service
metadata:
  name: ai-chat-ui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-chat-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 6501
