apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-gateway.fullname" . }}
  namespace: devops-ai
  labels:
    app: ai-gateway
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ai-gateway
  template:
    metadata:
      labels:
        app: ai-gateway
    spec:
      containers:
        - name: ai-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5002
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: outputs-volume
              mountPath: /app/outputs
      volumes:
        - name: outputs-volume
          hostPath:
            path: /mnt/data/gateway
            type: DirectoryOrCreate
