apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-gateway-outputs-pvc
  namespace: devops-ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
