apiVersion: v1
kind: Service
metadata:
  name: ai-gateway-service
  namespace: devops-ai
spec:
  selector:
    app: ai-gateway
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5002
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
